/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { BigNumber, BigNumberish } from 'ethers'
import { Contract } from 'starknet'

export class SwapRouter extends Contract {

  exact_input(
    token_in: BigNumberish,
    token_out: BigNumberish,
    fee: BigNumberish,
    recipient: BigNumberish,
    amount_in: BigNumberish,
    sqrt_price_limit: BigNumberish,
    amount_out_min: BigNumberish,
    deadline: BigNumberish
  ): Promise<{
    amount_out: BigNumberish
  }>

  exact_input_router(
    path_len: BigNumberish,
    path: BigNumberish[],
    recipient: BigNumberish,
    amount_in: BigNumberish,
    amount_out_min: BigNumberish,
    deadline: BigNumberish
  ): Promise<{
    amount_out: BigNumberish
  }>

  exact_output(
    token_in: BigNumberish,
    token_out: BigNumberish,
    fee: BigNumberish,
    recipient: BigNumberish,
    amount_out: BigNumberish,
    sqrt_price_limit: BigNumberish,
    amount_in_max: BigNumberish,
    deadline: BigNumberish
  ): Promise<{
    amount_in: BigNumberish
  }>

  exact_output_router(
    path_len: BigNumberish,
    path: BigNumberish[],
    recipient: BigNumberish,
    amount_out: BigNumberish,
    amount_in_max: BigNumberish,
    deadline: BigNumberish
  ): Promise<{
    amount_in: BigNumberish
  }>
}
