/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { BigNumber, BigNumberish } from 'ethers'
import { Contract } from 'starknet'

export class SwapQuoter extends Contract {
  get_exact_output(
    token_in: BigNumberish,
    token_out: BigNumberish,
    fee: BigNumberish,
    amount_out: BigNumberish
  ): Promise<{
    amount_in: BigNumberish
  }>

  get_exact_output_router(
    path_len: BigNumberish,
    path: BigNumberish[],
    amount_out: BigNumberish
  ): Promise<{
    amount_in: BigNumberish
  }>

  get_exact_input(
    token_in: BigNumberish,
    token_out: BigNumberish,
    fee: BigNumberish,
    amount_in: BigNumberish
  ): Promise<{
    amount_out: BigNumberish
  }>

  get_exact_input_router(
    path_len: BigNumberish,
    path: BigNumberish[],
    amount_in: BigNumberish
  ): Promise<{
    amount_out: BigNumberish
  }>

}
